US = {
    "Alabama": "Montgomery",
    "Alaska": "Juneau",
    "Arizona": "Phoenix",
    "Arkansas": "Little Rock",
    "California": "Sacramento",
    "Colorado": "Denver",
    "Connecticut": "Hartford",
    "Delaware": "Dover",
    "Florida": "Tallahassee",
    "Georgia": "Atlanta",
    "Hawaii": "Honolulu",
    "Idaho": "Boise",
    "Illinois": "Springfield",
    "Indiana": "Indianapolis",
    "Iowa": "Des Moines",
    "Kansas": "Topeka",
    "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge",
    "Maine": "Augusta",
    "Maryland": "Annapolis",
    "Massachusetts": "Boston",
    "Michigan": "Lansing",
    "Minnesota": "Saint Paul",
    "Mississippi": "Jackson",
    "Missouri": "Jefferson City",
    "Montana": "Helena",
    "Nebraska": "Lincoln",
    "Nevada": "Carson City",
    "New Hampshire": "Concord",
    "New Jersey": "Trenton",
    "New Mexico": "Santa Fe",
    "New York": "Albany",
    "North Carolina": "Raleigh",
    "North Dakota": "Bismarck",
    "Ohio": "Columbus",
    "Oklahoma": "Oklahoma City",
    "Oregon": "Salem",
    "Pennsylvania": "Harrisburg",
    "Rhode Island": "Providence",
    "South Carolina": "Columbia",
    "South Dakota": "Pierre",
    "Tennessee": "Nashville",
    "Texas": "Austin",
    "Utah": "Salt Lake City",
    "Vermont": "Montpelier",
    "Virginia": "Richmond",
    "Washington": "Olympia",
    "West Virginia": "Charleston",
    "Wisconsin": "Madison",
    "Wyoming": "Cheyenne"
}

NORTH_AMERICA = {
    "Canada": "Ottawa",
    "United States": "Washington, D.C.",
    "Mexico": "Mexico City",
    "Belize": "Belmopan",
    "Costa Rica": "San José",
    "El Salvador": "San Salvador",
    "Guatemala": "Guatemala City",
    "Honduras": "Tegucigalpa",
    "Nicaragua": "Managua",
    "Panama": "Panama City",
    "Greenland": "Nuuk",
    "Bermuda": "Hamilton"
}

CARIBBEAN = {
    # Sovereign countries
    "Antigua and Barbuda": "Saint John's",
    "Bahamas": "Nassau",
    "Barbados": "Bridgetown",
    "Cuba": "Havana",
    "Dominica": "Roseau",
    "Dominican Republic": "Santo Domingo",
    "Grenada": "Saint George's",
    "Haiti": "Port-au-Prince",
    "Jamaica": "Kingston",
    "Saint Kitts and Nevis": "Basseterre",
    "Saint Lucia": "Castries",
    "Saint Vincent and the Grenadines": "Kingstown",
    "Trinidad and Tobago": "Port of Spain",

    # British Overseas Territories
    "Anguilla (UK)": "The Valley",
    "Bermuda (UK)": "Hamilton",
    "British Virgin Islands (UK)": "Road Town",
    "Cayman Islands (UK)": "George Town",
    "Montserrat (UK)": ["Plymouth", "Brades"], # offical vs defacto
    "Turks and Caicos Islands (UK)": "Cockburn Town",

    # US Territories
    "Puerto Rico (US)": "San Juan",
    "U.S. Virgin Islands (US)": "Charlotte Amalie",

    # French Territories
    "Guadeloupe (France)": "Basse-Terre",
    "Martinique (France)": "Fort-de-France",
    "Saint Barthélemy (France)": "Gustavia",
    "Saint Martin (France)": "Marigot",

    # Dutch Territories
    "Aruba (Netherlands)": "Oranjestad",
    "Curaçao (Netherlands)": "Willemstad",
    "Sint Maarten (Netherlands)": "Philipsburg",
    "Bonaire (Netherlands)": "Kralendijk",
    "Saba (Netherlands)": "The Bottom",
    "Sint Eustatius (Netherlands)": "Oranjestad"
}

SOUTH_AMERICA = {
    "Argentina": "Buenos Aires",
    "Bolivia": ["Sucre", "La Paz"],  # Sucre is the constitutional capital; La Paz is the seat of government
    "Brazil": "Brasília",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "Ecuador": "Quito",
    "Guyana": "Georgetown",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Suriname": "Paramaribo",
    "Uruguay": "Montevideo",
    "Venezuela": "Caracas",
    "French Guiana (France)": "Cayenne",
    "Falkland Islands (UK)": "Stanley"
}

EUROPE = {
    "Albania": "Tirana",
    "Andorra": "Andorra la Vella",
    "Austria": "Vienna",
    "Belarus": "Minsk",
    "Belgium": "Brussels",
    "Bosnia and Herzegovina": "Sarajevo",
    "Bulgaria": "Sofia",
    "Croatia": "Zagreb",
    "Cyprus": "Nicosia",
    "Czech Republic": "Prague",
    "Denmark": "Copenhagen",
    "Estonia": "Tallinn",
    "Finland": "Helsinki",
    "France": "Paris",
    "Germany": "Berlin",
    "Greece": "Athens",
    "Hungary": "Budapest",
    "Iceland": "Reykjavík",
    "Ireland": "Dublin",
    "Italy": "Rome",
    "Kosovo": "Pristina",
    "Latvia": "Riga",
    "Liechtenstein": "Vaduz",
    "Lithuania": "Vilnius",
    "Luxembourg": "Luxembourg",
    "Malta": "Valletta",
    "Moldova": "Chișinău",
    "Monaco": "Monaco",
    "Montenegro": "Podgorica",
    "Netherlands": "Amsterdam",
    "North Macedonia": "Skopje",
    "Norway": "Oslo",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Romania": "Bucharest",
    "Russia": "Moscow",
    "San Marino": "San Marino",
    "Serbia": "Belgrade",
    "Slovakia": "Bratislava",
    "Slovenia": "Ljubljana",
    "Spain": "Madrid",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Ukraine": "Kyiv",
    "United Kingdom": "London",
    "Vatican City": "Vatican City",

    # Disputed / partially recognized regions
    "Crimea": "Simferopol",
    "Transnistria": "Tiraspol",

    # Territories
    "Gibraltar (UK)": "Gibraltar",
    "Isle of Man (UK)": "Douglas",
    "Jersey (UK)": "Saint Helier",
    "Guernsey (UK)": "Saint Peter Port",
    "Faroe Islands (Denmark)": "Tórshavn"
}

AFRICA = {
    "Algeria": "Algiers",
    "Angola": "Luanda",
    "Benin": "Porto-Novo",
    "Botswana": "Gaborone",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Cabo Verde": "Praia",
    "Cameroon": "Yaoundé",
    "Central African Republic": "Bangui",
    "Chad": "N'Djamena",
    "Comoros": "Moroni",
    "Côte d'Ivoire": ["Yamoussoukro", "Abidjan"],  # official vs governmental
    "DR Congo": "Kinshasa",
    "Republic of the Congo": "Brazzaville",
    "Djibouti": "Djibouti City",
    "Egypt": "Cairo",
    "Equatorial Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Eswatini": ["Mbabane", "Lobamba"],  # administrative vs legislative
    "Ethiopia": "Addis Ababa",
    "Gabon": "Libreville",
    "The Gambia": "Banjul",
    "Ghana": "Accra",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Kenya": "Nairobi",
    "Lesotho": "Maseru",
    "Liberia": "Monrovia",
    "Libya": "Tripoli",
    "Madagascar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Mali": "Bamako",
    "Mauritania": "Nouakchott",
    "Mauritius": "Port Louis",
    "Morocco": "Rabat",
    "Mozambique": "Maputo",
    "Namibia": "Windhoek",
    "Niger": "Niamey",
    "Nigeria": "Abuja",
    "Rwanda": "Kigali",
    "São Tomé and Príncipe": "São Tomé",
    "Senegal": "Dakar",
    "Seychelles": "Victoria",
    "Sierra Leone": "Freetown",
    "Somalia": "Mogadishu",
    "South Africa": ["Pretoria", "Cape Town", "Bloemfontein"],
    "South Sudan": "Juba",
    "Sudan": "Khartoum",
    "Tanzania": "Dodoma",
    "Togo": "Lomé",
    "Tunisia": "Tunis",
    "Uganda": "Kampala",
    "Zambia": "Lusaka",
    "Zimbabwe": "Harare",

    # Disputed/partially‑recognized
    "Western Sahara": ["Laayoune", "Tifariti"],  # proclaimed vs de facto administration
    "Somaliland": "Hargeisa",
    "Darfur": "Al-Fashir",
}

ASIA = {
    # Sovereign states (widely recognized)
    "Afghanistan": "Kabul",
    "Armenia": "Yerevan",
    "Azerbaijan": "Baku",
    "Bahrain": "Manama",
    "Bangladesh": "Dhaka",
    "Bhutan": "Thimphu",
    "Brunei": "Bandar Seri Begawan",
    "Cambodia": "Phnom Penh",
    "China": "Beijing",
    "Georgia": "Tbilisi",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Israel": "Jerusalem",
    "Japan": "Tokyo",
    "Jordan": "Amman",
    "Kazakhstan": "Astana",
    "Kuwait": "Kuwait City",
    "Kyrgyzstan": "Bishkek",
    "Laos": "Vientiane",
    "Lebanon": "Beirut",
    "Malaysia": ["Kuala Lumpur", "Putrajaya"],  # official vs administrative
    "Maldives": "Malé",
    "Mongolia": "Ulaanbaatar",
    "Myanmar": "Naypyidaw",
    "Nepal": "Kathmandu",
    "North Korea": "Pyongyang",
    "Oman": "Muscat",
    "Pakistan": "Islamabad",
    "Philippines": "Manila",
    "Qatar": "Doha",
    "Russia": "Moscow",
    "Saudi Arabia": "Riyadh",
    "Singapore": "Singapore",
    "South Korea": "Seoul",
    "Sri Lanka": ["Sri Jayawardenepura Kotte", "Colombo"],  # legislative vs commercial
    "Syria": "Damascus",
    "Tajikistan": "Dushanbe",
    "Thailand": "Bangkok",
    "Timor-Leste": "Dili",
    "Turkey": "Ankara",
    "Turkmenistan": "Ashgabat",
    "United Arab Emirates": "Abu Dhabi",
    "Uzbekistan": "Tashkent",
    "Vietnam": "Hanoi",
    "Yemen": ["Sana'a", "Aden"],  # de jure vs interim seat

    # Disputed / partially recognized / autonomous entities
    "Taiwan": "Taipei",
    "Palestine": ["Ramallah", "East Jerusalem"],
    "Northern Cyprus": "North Nicosia",
    "Abkhazia": "Sukhumi",
    "South Ossetia": "Tskhinvali",
    "Artsakh (Nagorno-Karabakh)": "Stepanakert",
    "Kurdistan (Iraqi Kurdistan Region)": "Erbil",
    "Hong Kong (China SAR)": "Hong Kong",
    "Macau (China SAR)": "Macau",
    "Tibet (AUT within China)": "Lhasa"
}

OCEANIA = {
    # Sovereign states
    "Australia": "Canberra",
    "Fiji": "Suva",
    "Kiribati": "Tarawa",
    "Marshall Islands": "Majuro",
    "Micronesia (Federated States of)": "Palikir",
    "Nauru": "Yaren",  # Nauru has no official capital, Yaren acts as government seat
    "New Zealand": "Wellington",
    "Palau": "Ngerulmud",
    "Papua New Guinea": "Port Moresby",
    "Samoa": "Apia",
    "Solomon Islands": "Honiara",
    "Tonga": "Nuku'alofa",
    "Tuvalu": "Funafuti",
    "Vanuatu": "Port Vila",

    # Territories and dependencies
    "American Samoa (US)": "Pago Pago",
    "Cook Islands (NZ)": "Avarua",
    "French Polynesia (France)": "Papeete",
    "Guam (US)": "Hagåtña",
    "New Caledonia (France)": "Nouméa",
    "Niue (NZ)": "Alofi",
    "Norfolk Island (Australia)": "Kingston",
    "Northern Mariana Islands (US)": "Saipan",
    "Pitcairn Islands (UK)": "Adamstown",
    "Tokelau (NZ)": "Nukunonu",
    "Wallis and Futuna (France)": "Mata-Utu",

    # Autonomous / disputed region
    "Bougainville (PNG)": "Buka"
}

class Capitals():
    def __init__(self):
        self.capitals = {
            "us": US,
            "north america": NORTH_AMERICA,
            "south america": SOUTH_AMERICA,
            "caribbean": CARIBBEAN,
            "europe": EUROPE,
            "africa": AFRICA,
            "asia": ASIA,
            "oceania": OCEANIA
        }
